<?php

class PhotosDatabaseSeeder extends Seeder {

    public function run()
    {
        
      Photo::create(['user_id'=>1,'name'=>'Lorem Ipsum', 'description'=>'Fotografia incrível.','state'=>'SP','street'=>'Rua Castro Alves', 'tombo'=>'2', 'project_author'=>'Nome do autor da obra', 'workdate'=>'10-10-10', 'dataUpload'=>'11-11-11', 'dataCriacao'=>'12-12-12', 'country'=>'Brasil', 'collection'=>'Coleção', 'city'=>'São Paulo']);
      Photo::create(['user_id'=>1,'name'=>'Dolor Amet', 'description'=>'Mais uma fotografia incrível.','state'=>'SP','street'=>'Rua Ponta Porã', 'tombo'=>'2', 'project_author'=>'Nome do autor da obra', 'workdate'=>'10-10-10', 'dataUpload'=>'11-11-11', 'dataCriacao'=>'12-12-12', 'country'=>'Brasil', 'collection'=>'Coleção', 'city'=>'São Paulo']);
      Photo::create(['user_id'=>2,'name'=>'Lorem Ipsum', 'description'=>'Fotografia incrível.','state'=>'SP','street'=>'Rua Castro Alves', 'tombo'=>'2', 'project_author'=>'Nome do autor da obra', 'workdate'=>'10-10-10', 'dataUpload'=>'11-11-11', 'dataCriacao'=>'12-12-12', 'country'=>'Brasil', 'collection'=>'Coleção', 'city'=>'São Paulo']);
      Photo::create(['user_id'=>1 ,'name'=>'Dolor Amet', 'description'=>'Mais uma fotografia incrível.','state'=>'SP','street'=>'Rua Ponta Porã', 'tombo'=>'2', 'project_author'=>'Nome do autor da obra', 'workdate'=>'10-10-10', 'dataUpload'=>'11-11-11', 'dataCriacao'=>'12-12-12', 'country'=>'Brasil', 'collection'=>'Coleção', 'city'=>'São Paulo']);
      Photo::create(['user_id'=>1 ,'name'=>'Dolor Amet', 'description'=>'Uma fotografia incrível.','state'=>'SP','street'=>'Rua Ponta Porã', 'tombo'=>'2', 'project_author'=>'Nome do autor da obra', 'workdate'=>'10-10-10', 'dataUpload'=>'11-11-11', 'dataCriacao'=>'12-12-12', 'country'=>'Brasil', 'collection'=>'Coleção', 'city'=>'São Paulo']);
      Photo::create(['user_id'=>2 ,'name'=>'Donec mollis purus sapien', 'description'=>'Mais uma fotografia bela.','state'=>'SP','street'=>'Rua Ponta Porã', 'tombo'=>'2', 'project_author'=>'Nome do autor da obra', 'workdate'=>'10-10-10', 'dataUpload'=>'11-11-11', 'dataCriacao'=>'12-12-12', 'country'=>'Brasil', 'collection'=>'Coleção', 'city'=>'São Paulo']);
      Photo::create(['user_id'=>1 ,'name'=>'Curabitur in sem eget', 'description'=>'Mais uma fotografia fantástica.','state'=>'SP','street'=>'Rua Ponta Porã', 'tombo'=>'2', 'project_author'=>'Nome do autor da obra', 'workdate'=>'10-10-10', 'dataUpload'=>'11-11-11', 'dataCriacao'=>'12-12-12', 'country'=>'Brasil', 'collection'=>'Coleção', 'city'=>'São Paulo']);
      Photo::create(['user_id'=>1 ,'name'=>'Dolor Amet', 'description'=>'Uma fotografia de arquitetura.','state'=>'SP','street'=>'Rua Ponta Porã', 'tombo'=>'2', 'project_author'=>'Nome do autor da obra', 'workdate'=>'10-10-10', 'dataUpload'=>'11-11-11', 'dataCriacao'=>'12-12-12', 'country'=>'Brasil', 'collection'=>'Coleção', 'city'=>'São Paulo']);
      Photo::create(['user_id'=>1 ,'name'=>'Quisque id velit dui', 'description'=>'Mais uma fotografia incrível.','state'=>'SP','street'=>'Rua Ponta Porã', 'tombo'=>'2', 'project_author'=>'Nome do autor da obra', 'workdate'=>'10-10-10', 'dataUpload'=>'11-11-11', 'dataCriacao'=>'12-12-12', 'country'=>'Brasil', 'collection'=>'Coleção', 'city'=>'São Paulo']);
      Photo::create(['user_id'=>1 ,'name'=>'Dolor Amet', 'description'=>'Uma fotografia bela.','state'=>'SP','street'=>'Rua Ponta Porã', 'tombo'=>'2', 'project_author'=>'Nome do autor da obra', 'workdate'=>'10-10-10', 'dataUpload'=>'11-11-11', 'dataCriacao'=>'12-12-12', 'country'=>'Brasil', 'collection'=>'Coleção', 'city'=>'São Paulo']);
      Photo::create(['user_id'=>2 ,'name'=>'Quisque id velit dui', 'description'=>'Mais uma fotografia incrível.','state'=>'SP','street'=>'Rua Ponta Porã', 'tombo'=>'2', 'project_author'=>'Nome do autor da obra', 'workdate'=>'10-10-10', 'dataUpload'=>'11-11-11', 'dataCriacao'=>'12-12-12', 'country'=>'Brasil', 'collection'=>'Coleção', 'city'=>'São Paulo']);
      Photo::create(['user_id'=>2 ,'name'=>'Dolor Amet', 'description'=>'Novamente uma fotografia fantástica.','state'=>'SP','street'=>'Rua Ponta Porã', 'tombo'=>'2', 'project_author'=>'Nome do autor da obra', 'workdate'=>'10-10-10', 'dataUpload'=>'11-11-11', 'dataCriacao'=>'12-12-12', 'country'=>'Brasil', 'collection'=>'Coleção', 'city'=>'São Paulo']);
      Photo::create(['user_id'=>2 ,'name'=>'Dolor Amet', 'description'=>'Mais uma fotografia incrível.','state'=>'SP','street'=>'Rua Ponta Porã', 'tombo'=>'2', 'project_author'=>'Nome do autor da obra', 'workdate'=>'10-10-10', 'dataUpload'=>'11-11-11', 'dataCriacao'=>'12-12-12', 'country'=>'Brasil', 'collection'=>'Coleção', 'city'=>'São Paulo']);
      Photo::create(['user_id'=>1 ,'name'=>'Curabitur in sem eget', 'description'=>'Mais uma fotografia fantástica.','state'=>'SP','street'=>'Rua Ponta Porã', 'tombo'=>'2', 'project_author'=>'Nome do autor da obra', 'workdate'=>'10-10-10', 'dataUpload'=>'11-11-11', 'dataCriacao'=>'12-12-12', 'country'=>'Brasil', 'collection'=>'Coleção', 'city'=>'São Paulo']);
      Photo::create(['user_id'=>1 ,'name'=>'Dolor Amet', 'description'=>'Novamente uma fotografia bela.','state'=>'SP','street'=>'Rua Ponta Porã', 'tombo'=>'2', 'project_author'=>'Nome do autor da obra', 'workdate'=>'10-10-10', 'dataUpload'=>'11-11-11', 'dataCriacao'=>'12-12-12', 'country'=>'Brasil', 'collection'=>'Coleção', 'city'=>'São Paulo']);
      Photo::create(['user_id'=>1 ,'name'=>'Dolor Amet', 'description'=>'Mais uma fotografia fantástica.','state'=>'SP','street'=>'Rua Ponta Porã', 'tombo'=>'2', 'project_author'=>'Nome do autor da obra', 'workdate'=>'10-10-10', 'dataUpload'=>'11-11-11', 'dataCriacao'=>'12-12-12', 'country'=>'Brasil', 'collection'=>'Coleção', 'city'=>'São Paulo']);
      Photo::create(['user_id'=>1 ,'name'=>'Dolor Amet', 'description'=>'Mais uma fotografia incrível.','state'=>'SP','street'=>'Rua Ponta Porã', 'tombo'=>'2', 'project_author'=>'Nome do autor da obra', 'workdate'=>'10-10-10', 'dataUpload'=>'11-11-11', 'dataCriacao'=>'12-12-12', 'country'=>'Brasil', 'collection'=>'Coleção', 'city'=>'São Paulo']);
      Photo::create(['user_id'=>2 ,'name'=>'Dolor Amet', 'description'=>'Uma fotografia fantástica.','state'=>'SP','street'=>'Rua Ponta Porã', 'tombo'=>'2', 'project_author'=>'Nome do autor da obra', 'workdate'=>'10-10-10', 'dataUpload'=>'11-11-11', 'dataCriacao'=>'12-12-12', 'country'=>'Brasil', 'collection'=>'Coleção', 'city'=>'São Paulo']);
      Photo::create(['user_id'=>1 ,'name'=>'Dolor Amet', 'description'=>'Mais uma fotografia bela.','state'=>'SP','street'=>'Rua Ponta Porã', 'tombo'=>'2', 'project_author'=>'Nome do autor da obra', 'workdate'=>'10-10-10', 'dataUpload'=>'11-11-11', 'dataCriacao'=>'12-12-12', 'country'=>'Brasil', 'collection'=>'Coleção', 'city'=>'São Paulo']);
      Photo::create(['user_id'=>1 ,'name'=>'Dolor Amet', 'description'=>'Mais uma fotografia fantástica.','state'=>'SP','street'=>'Rua Ponta Porã', 'tombo'=>'2', 'project_author'=>'Nome do autor da obra', 'workdate'=>'10-10-10', 'dataUpload'=>'11-11-11', 'dataCriacao'=>'12-12-12', 'country'=>'Brasil', 'collection'=>'Coleção', 'city'=>'São Paulo']);
      Photo::create(['user_id'=>1 ,'name'=>'Dolor Amet', 'description'=>'Novamente uma fotografia incrível.','state'=>'SP','street'=>'Rua Ponta Porã', 'tombo'=>'2', 'project_author'=>'Nome do autor da obra', 'workdate'=>'10-10-10', 'dataUpload'=>'11-11-11', 'dataCriacao'=>'12-12-12', 'country'=>'Brasil', 'collection'=>'Coleção', 'city'=>'São Paulo']);
      Photo::create(['user_id'=>2 ,'name'=>'Dolor Amet', 'description'=>'Uma fotografia fantástica.','state'=>'SP','street'=>'Rua Ponta Porã', 'tombo'=>'2', 'project_author'=>'Nome do autor da obra', 'workdate'=>'10-10-10', 'dataUpload'=>'11-11-11', 'dataCriacao'=>'12-12-12', 'country'=>'Brasil', 'collection'=>'Coleção', 'city'=>'São Paulo']);
      Photo::create(['user_id'=>2 ,'name'=>'Dolor Amet', 'description'=>'Mais uma fotografia bela.','state'=>'SP','street'=>'Rua Ponta Porã', 'tombo'=>'2', 'project_author'=>'Nome do autor da obra', 'workdate'=>'10-10-10', 'dataUpload'=>'11-11-11', 'dataCriacao'=>'12-12-12', 'country'=>'Brasil', 'collection'=>'Coleção', 'city'=>'São Paulo']);
      Photo::create(['user_id'=>2 ,'name'=>'Dolor Amet', 'description'=>'Mais uma fotografia incrível.','state'=>'SP','street'=>'Rua Ponta Porã', 'tombo'=>'2', 'project_author'=>'Nome do autor da obra', 'workdate'=>'10-10-10', 'dataUpload'=>'11-11-11', 'dataCriacao'=>'12-12-12', 'country'=>'Brasil', 'collection'=>'Coleção', 'city'=>'São Paulo']);
      Photo::create(['user_id'=>2 ,'name'=>'Dolor Amet', 'description'=>'Novamente uma fotografia incrível.','state'=>'SP','street'=>'Rua Ponta Porã', 'tombo'=>'2', 'project_author'=>'Nome do autor da obra', 'workdate'=>'10-10-10', 'dataUpload'=>'11-11-11', 'dataCriacao'=>'12-12-12', 'country'=>'Brasil', 'collection'=>'Coleção', 'city'=>'São Paulo']);
      Photo::create(['user_id'=>1 ,'name'=>'Dolor Amet', 'description'=>'Mais uma fotografia bela.','state'=>'SP','street'=>'Rua Ponta Porã', 'tombo'=>'2', 'project_author'=>'Nome do autor da obra', 'workdate'=>'10-10-10', 'dataUpload'=>'11-11-11', 'dataCriacao'=>'12-12-12', 'country'=>'Brasil', 'collection'=>'Coleção', 'city'=>'São Paulo']);
      Photo::create(['user_id'=>1 ,'name'=>'Dolor Amet', 'description'=>'Mais uma fotografia incrível.','state'=>'SP','street'=>'Rua Ponta Porã', 'tombo'=>'2', 'project_author'=>'Nome do autor da obra', 'workdate'=>'10-10-10', 'dataUpload'=>'11-11-11', 'dataCriacao'=>'12-12-12', 'country'=>'Brasil', 'collection'=>'Coleção', 'city'=>'São Paulo']);
      Photo::create(['user_id'=>1 ,'name'=>'Dolor Amet', 'description'=>'Novamente uma fantástica fotografia.','state'=>'SP','street'=>'Rua Ponta Porã', 'tombo'=>'2', 'project_author'=>'Nome do autor da obra', 'workdate'=>'10-10-10', 'dataUpload'=>'11-11-11', 'dataCriacao'=>'12-12-12', 'country'=>'Brasil', 'collection'=>'Coleção', 'city'=>'São Paulo']);
      Photo::create(['user_id'=>1 ,'name'=>'Dolor Amet', 'description'=>'Uma fotografia incrível.','state'=>'SP','street'=>'Rua Ponta Porã', 'tombo'=>'2', 'project_author'=>'Nome do autor da obra', 'workdate'=>'10-10-10', 'dataUpload'=>'11-11-11', 'dataCriacao'=>'12-12-12', 'country'=>'Brasil', 'collection'=>'Coleção', 'city'=>'São Paulo']);
    }

}